
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j.retry:
    instances:
      simpleRetry:
        maxAttempts: 2
        waitDuration: 2s
      retryOnException:
        maxAttempts: 3
        waitDuration: 5s
        retryExceptions:
          - org.springframework.web.client.HttpClientErrorException
        ignoreExceptions:
          - com.ms.exception.MovieNotFoundException
      retryBasedOnConditionalPredicate:
         maxAttempts: 2
         waitDuration: 5s
         resultPredicate: com.ms.predicate.ConditionPredicate
      retryBasedOnExceptionPredicate:
        maxAttempts: 3
        waitDuration: 4s
        retryExceptionPredicate: com.ms.predicate.ExceptionPredicate
      retryUsingExponentialBackoff:
        maxAttempts: 2
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      retryUsingRandomizedWait:
        maxAttempts: 4
        waitDuration: 2s
        enableRandomizedWait: true
        randomizedWaitFactor: 0.7
      retryWithEventDetails:
        maxAttempts: 3
        waitDuration: 5s
      
resilience4j.circuitbreaker:
  
  circuit-breaker-aspect-order: 1
  instances:
    greetingClientCB:
      registerHealthIndicator: true
      slidingWindowSize: 6
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      automatic-transition-from-open-to-half-open-enabled: true
#      slowCallRateThreshold: 100
#      slowCallDurationThreshold: 2000
      failureRateThreshold: 50
#      ignoreExceptions:
#        - com.jsession4d.feignclient.BusinessException  
        


        